#%RAML 1.0 DataType

description: Represents Flight properties
type: object  
properties: 
  ID?: string
  airline: string
  flightCode: string
  fromAirportCode: string
  toAirportCode: string
  departureDate: string
  emptySeats: integer
  totalSeats?: integer
  price: number
  planeType?: string 

